# add your desired knowledge graph components here
# Authors:  Matthieu Najm - Edwin Carreño

#--- Ontology: BioLink


#--------------------  Information about Nodes
source:
    is_a: protein
    represented_as: node
    input_label: source_protein # temporary node type
    properties:
        genesymbol: str
        ncbi_tax_id: str
        entity_type: str

target:
    is_a: protein
    represented_as: node
    input_label: target_protein # temporary node type
    properties:
        genesymbol: str
        ncbi_tax_id: str
        entity_type: str

protein:
    represented_as: node
    input_label: protein # final_type node type
    properties:
        genesymbol: str
        ncbi_tax_id: str
        entity_type: str

complex:
    is_a: molecular mixture
    represented_as: node
    input_label: complex # final_type node type
    properties:
        complex_genesymbol: str
        ncbi_tax_id: str
        # entity_type: str

small molecule:
    is_a: molecular mixture
    represented_as: node
    input_label: small_moelcule
    properties:
        name: str
        ncbi_tax_id: str
        # entity_type: str

#--------------------  Information about Edges
post translational:
    is_a: pairwise molecular interaction
    represented_as: edge
    input_label: post_translational
    properties:
        is_directed: bool
        is_stimulation: bool
        is_inhibition: bool
        consensus_direction: bool
        consensus_stimulation: bool
        consensus_inhibition: bool
        sources: str
        references: str
        omnipath: bool
        kinaseextra: bool
        ligrecextra: bool
        pathwayextra: bool
        dorothea: bool
        collectri: bool
        tf_target: bool
        lncrna_mrna: bool
        tf_mirna: bool
        small_molecule: bool
        dorothea_curated: bool
        dorothea_chipseq: bool
        dorothea_tfbs: bool
        dorothea_coexp: bool
        dorothea_level: str
        type: str
        curation_effort: str
        extra_attrs: str
        evidences: str

transcriptional:
    is_a: pairwise molecular interaction
    represented_as: edge
    input_label: transcriptional
    properties:
        is_directed: bool
        is_stimulation: bool
        is_inhibition: bool
        consensus_direction: bool
        consensus_stimulation: bool
        consensus_inhibition: bool
        sources: str
        references: str
        omnipath: bool
        kinaseextra: bool
        ligrecextra: bool
        pathwayextra: bool
        dorothea: bool
        collectri: bool
        tf_target: bool
        lncrna_mrna: bool
        tf_mirna: bool
        small_molecule: bool
        dorothea_curated: bool
        dorothea_chipseq: bool
        dorothea_tfbs: bool
        dorothea_coexp: bool
        dorothea_level: str
        type: str
        curation_effort: int
        extra_attrs: str
        evidences: str

post transcriptional:
    is_a: pairwise molecular interaction
    represented_as: edge
    input_label: post_transcriptional
    properties:
        is_directed: bool
        is_stimulation: bool
        is_inhibition: bool
        consensus_direction: bool
        consensus_stimulation: bool
        consensus_inhibition: bool
        sources: str
        references: str
        omnipath: bool
        kinaseextra: bool
        ligrecextra: bool
        pathwayextra: bool
        dorothea: bool
        collectri: bool
        tf_target: bool
        lncrna_mrna: bool
        tf_mirna: bool
        small_molecule: bool
        dorothea_curated: bool
        dorothea_chipseq: bool
        dorothea_tfbs: bool
        dorothea_coexp: bool
        dorothea_level: str
        type: str
        curation_effort: int
        extra_attrs: str
        evidences: str

mirna transcriptional:
    is_a: pairwise molecular interaction
    represented_as: edge
    input_label: mirna_transcriptional
    properties:
        is_directed: bool
        is_stimulation: bool
        is_inhibition: bool
        consensus_direction: bool
        consensus_stimulation: bool
        consensus_inhibition: bool
        sources: str
        references: str
        omnipath: bool
        kinaseextra: bool
        ligrecextra: bool
        pathwayextra: bool
        dorothea: bool
        collectri: bool
        tf_target: bool
        lncrna_mrna: bool
        tf_mirna: bool
        small_molecule: bool
        dorothea_curated: bool
        dorothea_chipseq: bool
        dorothea_tfbs: bool
        dorothea_coexp: bool
        dorothea_level: str
        type: str
        curation_effort: int
        extra_attrs: str
        evidences: str

lncrna post transcriptional:
    is_a: pairwise molecular interaction
    represented_as: edge
    input_label: lncrna_post_transcriptional
    properties:
        is_directed: bool
        is_stimulation: bool
        is_inhibition: bool
        consensus_direction: bool
        consensus_stimulation: bool
        consensus_inhibition: bool
        sources: str
        references: str
        omnipath: bool
        kinaseextra: bool
        ligrecextra: bool
        pathwayextra: bool
        dorothea: bool
        collectri: bool
        tf_target: bool
        lncrna_mrna: bool
        tf_mirna: bool
        small_molecule: bool
        dorothea_curated: bool
        dorothea_chipseq: bool
        dorothea_tfbs: bool
        dorothea_coexp: bool
        dorothea_level: str
        type: str
        curation_effort: int
        extra_attrs: str
        evidences: str

small molecule protein:
    is_a: pairwise molecular interaction
    represented_as: edge
    input_label: small_molecule_protein
    properties:
        is_directed: bool
        is_stimulation: bool
        is_inhibition: bool
        consensus_direction: bool
        consensus_stimulation: bool
        consensus_inhibition: bool
        sources: str
        references: str
        omnipath: bool
        kinaseextra: bool
        ligrecextra: bool
        pathwayextra: bool
        dorothea: bool
        collectri: bool
        tf_target: bool
        lncrna_mrna: bool
        tf_mirna: bool
        small_molecule: bool
        dorothea_curated: bool
        dorothea_chipseq: bool
        dorothea_tfbs: bool
        dorothea_coexp: bool
        dorothea_level: str
        type: str
        curation_effort: int
        extra_attrs: str
        evidences: str