# add your desired knowledge graph components here
# Authors:  Matthieu Najm - Edwin Carreño

#--- Ontology: BioLink


#--------------------  Information about Nodes
source complex:
    is_a: macromolecular complex
    represented_as: node
    input_label: source_complex # temporary node type
    properties:
        name: str
        ncbi_tax_id: str

target complex:
    is_a: macromolecular complex
    represented_as: node
    input_label: target_complex # temporary node type
    properties:
        name: str
        ncbi_tax_id: str

macromolecular complex:
    represented_as: node
    input_label: macromolecular_complex # final_type node type
    properties:
        name: str
        ncbi_tax_id: str

source lncrna:
    is_a: noncoding RNA product
    represented_as: node
    input_label: source_lncrna # temporary node type
    properties:
        name: str
        ncbi_tax_id: str

target lncrna:
    is_a: noncoding RNA product
    represented_as: node
    input_label: target_lncrna # temporary node type
    properties:
        name: str
        ncbi_tax_id: str

lncrna:
    is_a: noncoding RNA product
    represented_as: node
    input_label: lncrna # final_type node type
    properties:
        name: str
        ncbi_tax_id: str

source mirna:
    is_a: RNA product
    represented_as: node
    input_label: source_mirna # temporary node type
    properties:
        name: str
        ncbi_tax_id: str

target mirna:
    is_a: RNA product
    represented_as: node
    input_label: target_mirna # temporary node type
    properties:
        name: str
        ncbi_tax_id: str

mirna:
    is_a: RNA product
    represented_as: node
    input_label: mirna # final_type node type
    properties:
        name: str
        ncbi_tax_id: str

source protein:
    is_a: protein
    represented_as: node
    input_label: source_protein # temporary node type
    properties:
        name: str
        ncbi_tax_id: str

target protein:
    is_a: protein
    represented_as: node
    input_label: target_protein # temporary node type
    properties:
        name: str
        ncbi_tax_id: str

protein:
    represented_as: node
    input_label: protein # final_type node type
    properties:
        name: str
        ncbi_tax_id: str

source small molecule:
    is_a: small molecule
    represented_as: node
    input_label: source_small_molecule # temporary node type
    properties:
        name: str
        ncbi_tax_id: str

target small molecule:
    is_a: small molecule
    represented_as: node
    input_label: target_small_molecule # temporary node type
    properties:
        name: str
        ncbi_tax_id: str

small molecule:
    represented_as: node
    input_label: small_molecule # final_type node type
    properties:
        name: str
        ncbi_tax_id: str

#--------------------  Information about Edges
pairwise molecular interaction:
    represented_as: edge
    input_label: pairwise_molecular_interaction
    properties:
        is_directed: bool
        is_stimulation: bool
        is_inhibition: bool
        consensus_direction: bool
        consensus_stimulation: bool
        consensus_inhibition: bool
        sources: str
        references: str
        omnipath: bool
        kinaseextra: bool
        ligrecextra: bool
        pathwayextra: bool
        dorothea: bool
        collectri: bool
        tf_target: bool
        lncrna_mrna: bool
        tf_mirna: bool
        small_molecule: bool
        dorothea_curated: bool
        dorothea_chipseq: bool
        dorothea_tfbs: bool
        dorothea_coexp: bool
        dorothea_level: str
        type: str
        curation_effort: str
        extra_attrs: str
        evidences: str